=head1 NAME

title-help - Show help on Title and its commands

=head1 SYNOPSIS

C<title help [--console] [--no-pager]>

C<< title help E<lt>commandE<gt> [--console] [--no-pager] >>

=head1 DESCRIPTION

Show help on particular command (if it is provided), or general information about Title.
By default (and depending on your operating system), it will try to open an HTML version
of the help in your browser. Otherwise it will render a plain-text version in the console.

For the list of available commands, just run C<title> with no command-line parameters.

=head1 OPTIONS

=over 8

=item B<--console>

Do not try to open HTML help in browser; render help in console instead.

=item B<--no-pager>

When in console mode, do not try to use a pager. By default, Title tries to use C<less>
or C<more>. The pager command can be overwritten by C<TITLE_PAGER> or C<PAGER> environment
variables. To permanently disable the pager in Title, set C<TITLE_PAGER> to C<0>.

=back

=head1 SEE ALSO

Part of L<title> suite.
